#!/usr/bin/env python3
"""
Join ApiSurface.csv against src/docs/api/OASv3/ocs-api-service.yaml.

WHY THIS EXISTS
The OpenAPI file is generated by springdoc-openapi-gradle-plugin from the
*running* application. It is therefore a runtime-derived ground truth that is
independent of CodeQL, ast-grep and semgrep alike. Tool-vs-tool agreement only
tells you the tools are similar; tool-vs-runtime agreement tells you which one
is right.

On ocs-api-service @ develop the contract declares 366 operations against 369
method-level mapping annotations in Java, so the expected residual is small and
every item in it should be explainable (conditional registration, @Profile-gated
controllers, springdoc exclusions).

WHAT IT DOES NOT DO
It does not attempt path-template normalisation beyond the obvious. Spring writes
`/{id}` and OpenAPI writes `/{id}`, but Spring also allows `/{id:[0-9]+}` and
class-level prefixes must be concatenated with method-level suffixes. Where the
join is ambiguous the row lands in `unmatched_*` rather than being force-fitted.
Silent fuzzy matching would manufacture the agreement this script exists to test.
"""

from __future__ import annotations

import argparse
import csv
import json
import re
import sys
from collections import defaultdict
from pathlib import Path

HTTP_METHODS = {"get", "put", "post", "delete", "patch", "head", "options", "trace"}


def load_openapi(path: Path) -> set[tuple[str, str]]:
    """Return {(METHOD, path)} from an OpenAPI 3 document."""
    text = path.read_text(encoding="utf-8")
    try:
        import yaml  # type: ignore

        doc = yaml.safe_load(text)
    except ImportError:
        print(
            "PyYAML not installed; falling back to a structural regex scan. "
            "Install PyYAML for an exact parse.",
            file=sys.stderr,
        )
        return _scan_openapi_text(text)

    ops: set[tuple[str, str]] = set()
    for route, item in (doc.get("paths") or {}).items():
        if not isinstance(item, dict):
            continue
        for verb in item:
            if verb.lower() in HTTP_METHODS:
                ops.add((verb.upper(), route))
    return ops


def _scan_openapi_text(text: str) -> set[tuple[str, str]]:
    """Indentation-based fallback parse. Assumes 2-space indent under `paths:`."""
    ops: set[tuple[str, str]] = set()
    route = None
    in_paths = False
    for line in text.splitlines():
        if re.match(r"^paths:\s*$", line):
            in_paths = True
            continue
        if in_paths and re.match(r"^\S", line):
            in_paths = False
        if not in_paths:
            continue
        m = re.match(r"^  (/\S*):\s*$", line)
        if m:
            route = m.group(1)
            continue
        m = re.match(r"^    ([a-z]+):\s*$", line)
        if m and route and m.group(1) in HTTP_METHODS:
            ops.add((m.group(1).upper(), route))
    return ops


def normalize_path(p: str) -> str:
    """Collapse Spring path templates toward the OpenAPI rendering."""
    if not p:
        return ""
    p = p.strip()
    # `{id:[0-9]+}` -> `{id}`
    p = re.sub(r"\{(\w+)\s*:[^}]*\}", r"{\1}", p)
    p = re.sub(r"/{2,}", "/", p)
    if not p.startswith("/"):
        p = "/" + p
    if len(p) > 1 and p.endswith("/"):
        p = p[:-1]
    return p


def load_api_surface(path: Path):
    """Return (prefix_by_class, endpoints) from ApiSurface.csv."""
    prefixes: dict[str, list[str]] = defaultdict(list)
    endpoints = []
    with path.open(newline="", encoding="utf-8") as fh:
        for row in csv.DictReader(fh):
            rule = row["rule_id"]
            if rule == "api_surface__path_prefix":
                # symbol is the class name; detail is "<METHOD> <path>"
                for part in row["detail"].split(" ", 1)[-1].split("|"):
                    if part:
                        prefixes[row["symbol"]].append(normalize_path(part))
            elif rule == "api_surface__endpoint":
                verb, _, raw_path = row["detail"].partition(" ")
                # Method symbols are pkg/Class#method().; the class prefix key is
                # pkg/Class#. rsplit on '.' was wrong and always missed the prefix.
                owner = row["symbol"].split("#", 1)[0] + "#"
                endpoints.append(
                    {
                        "file": row["file"],
                        "line": row["start_line"],
                        "symbol": row["symbol"],
                        "owner": owner,
                        "verb": verb.strip(),
                        "suffixes": [normalize_path(s) for s in raw_path.split("|") if s]
                        or [""],
                    }
                )
    return prefixes, endpoints


def expand(prefixes, endpoints) -> dict[tuple[str, str], list[dict]]:
    """Cross class-level prefixes with method-level suffixes."""
    out: dict[tuple[str, str], list[dict]] = defaultdict(list)
    for ep in endpoints:
        bases = prefixes.get(ep["owner"]) or [""]
        verbs = [v for v in ep["verb"].split("|") if v] or ["ANY"]
        for base in bases:
            for suffix in ep["suffixes"]:
                full = normalize_path(base + suffix) if (base or suffix) else "/"
                for verb in verbs:
                    out[(verb, full)].append(ep)
    return out


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--api-surface", required=True, type=Path)
    ap.add_argument("--openapi", required=True, type=Path)
    ap.add_argument("--out", type=Path, default=Path("out/openapi_join.json"))
    args = ap.parse_args()

    spec_ops = load_openapi(args.openapi)
    prefixes, endpoints = load_api_surface(args.api_surface)
    code_ops = expand(prefixes, endpoints)

    matched = sorted(set(code_ops) & spec_ops)
    only_code = sorted(set(code_ops) - spec_ops)
    only_spec = sorted(spec_ops - set(code_ops))

    report = {
        "counts": {
            "spec_operations": len(spec_ops),
            "code_endpoint_annotations": len(endpoints),
            "code_operations_expanded": len(code_ops),
            "matched": len(matched),
            "unmatched_code_only": len(only_code),
            "unmatched_spec_only": len(only_spec),
        },
        "unmatched_code_only": [
            {
                "verb": v,
                "path": p,
                "sites": [f"{e['file']}:{e['line']} {e['symbol']}" for e in code_ops[(v, p)]],
            }
            for v, p in only_code
        ],
        "unmatched_spec_only": [{"verb": v, "path": p} for v, p in only_spec],
    }

    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(json.dumps(report, indent=2), encoding="utf-8")

    c = report["counts"]
    print(f"spec operations          : {c['spec_operations']}")
    print(f"code endpoint annotations: {c['code_endpoint_annotations']}")
    print(f"code operations expanded : {c['code_operations_expanded']}")
    print(f"matched                  : {c['matched']}")
    print(f"code-only (unmatched)    : {c['unmatched_code_only']}")
    print(f"spec-only (unmatched)    : {c['unmatched_spec_only']}")
    print(f"\nwrote {args.out}")
    print(
        "\nEvery unmatched row is a finding about the JOIN or the TOOL, not noise. "
        "Explain them individually before quoting a recall number."
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
